name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_0218F331E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # Point to the source code root
          api_location: "" # Api source code path - optional
          output_location: "dist-${{ github.run_id }}" # Unique output directory for each build
          ###### End of Repository/Build Configurations ######
        env:
          # Azure Oryx Build Configuration - Multiple ways to specify Node.js 20
          ORYX_NODE_VERSION: "20"
          NODE_VERSION: "20"
          WEBSITE_NODE_DEFAULT_VERSION: "20.x"
          
          # Core Application Variables
          VITE_APP_TITLE: Agile Mantis - Production
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          
          # Auth0 Configuration
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_AUTH0_AUDIENCE: ${{ secrets.VITE_AUTH0_AUDIENCE }}
          VITE_AUTH0_REDIRECT_URI: https://calm-sky-0218f331e.azurestaticapps.net/callback
          
          # Production Settings
          VITE_ENVIRONMENT: production
          VITE_LOG_LEVEL: info

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SKY_0218F331E }}
          action: "close"
